aritra0342/Resume_generator

- script.js
Issue #3 fixed. 
In the final resume, if the user left a field blank, then the heading of that field will not show at all.
@aritra0342 assignment done 😁✅
> Fix #3: Headings no longer display on resume if fields are empty

- index.html
- script.js
- style.css
This pull request introduces the following changes to enhance the resume generator:
Fixes : #5 
- **DOCX Export:**
- Added a new function **(exportToDocx())** that leverages the **docx** library to export the resume as a DOCX file.
- Updated the resume output to include a **"Export as DOCX**" button.
**Screenshot:**
> Added DOCX export functionality

- index.html
- script.js
- style.css
Fix #1
- Added span containing asterisk to required fields (while editing)
- Modified script.js to hide asterisk on final resume printout
- Used css to display none of the asterisk on resume
> Indicate required fields

- index.html
- script.js
- style.css
i have added a button in which the candidate will select a profile picture and it will generate the resume with profile picture.
> Adding the extra button in form to add the profile picture of a candidate

- index.html
- script.js
- style.css
introduces character limits for various resume fields to enhance formatting and prevent layout issues caused by excessively long text inputs.
**Changes Implemented:**
✅ Added character limits for key fields:
- Name: 50 characters
- Summary: 250 characters
- Experience Description: 500 characters
- Skills: 100 characters
✅ Ensured truncation does not break words when rendering the resume.
✅ Updated form validation to prevent users from exceeding limits.
> Added character limits to resume fields to improve layout

- index.html
- script.js
- style.css
📌 Summary
This PR adds a new feature to allow users to input certificates along with their respective links. The enhancement improves the user experience by making it easier to showcase certifications with direct access to the proof of completion.
🔨 Changes Made
Added input fields for Certificate Name and Certificate Link (URL).
Updated index.html to include these input fields.
Improved style.css to ensure proper layout and full-width block elements.
Modified script.js to handle dynamic addition and removal of certificate entries.
🔗 Related Issue
This PR addresses Issue #23.
🌍 Open Source Program
This contribution is made as part of Aperture 2.0.
✅ How to Test
Open the index.html file in a browser.
Navigate to the certificate section.
Add a certificate name and its corresponding link. …
> Enhace certificate input field and add link option

- index.html
- style.css
Fixed Form Spacing and Add Hover Effect
Description:
This PR addresses [#29] by resolving the form layout inconsistencies and enhancing user experience with a hover effect.
Changes Implemented:
Adjusted form spacing to ensure a more symmetric and visually balanced layout.
Added a hover effect on form sections for improved interactivity.
Issue Reference:
This PR is made in response to the issue discussed here[#29], for which I was granted permission.
Before & After:
Attach screenshots  highlighting the changes.
BEFORE:
AFTER:
> Fix Overlap of Upper Form Elements and Add Interactive Hover Effects for a Clearer Layout. #29

- index.html
- script.js
- style.css
- Removed the feature of resizing the textarea elements.
- Modified the 'Remove' button in the "Certification" field.
> Remove Resizing of Textareas and UI Enhancement

- index.html
- script.js
- style.css
- Changed display of contact info - email, telephone, LinkedIn and Github
- Added a line to make Contact details distinct
- Changed display of job title 
- Screenshot of sample below
> Fix #2: Enhance UI

- index.html
- landing-page.css
- landing-page.html
#close31 
https://1drv.ms/i/c/516261692c9015c0/EblPP_PEhBxBsWfVV_JGFiYBmj-Y35ShBcyGf1LQCYaESw
> Add landing page to the "Resume Generator" project.

- style.css
> Added back to top button

- script.js
**Original version: -**
Resume Output
**After change: -**
After resume generation, it would look this
> Did small change for asterisk remover

- index.html
- script.js
- style.css
Fixes : #17 
- Implemented a live preview panel that updates instantly as users type.
- Ensured real-time synchronization when users:
- Modify text fields (e.g., name, contact, experience, education).
- Add or remove sections.
**Screenshots:**
https://github.com/user-attachments/assets/f8840fbb-36a5-4ae2-8427-474f3fa9d945
>  Add Real-Time Resume Preview Feature

- script.js
- style.css
PR for Issue #50 
Issue Addressed:
1) **Live Preview Box Not Fixed on Scrolling:**
Users had to scroll back up frequently to check their resume preview, making the form-filling process inconvenient.
This was particularly frustrating while filling out the lower sections of the form, as previewing changes required constant navigation.
2) **Overlapping UI & Poor Spacing:**
The Resume Form and Live Preview Box were overlapping, leading to a cluttered layout.
There were no proper borders or spacing, reducing the visual clarity and user experience.
1) Live Preview Box is now sticky at the top – Users can now see real-time updates without unnecessary scrolling.
2) Improved UI & Styling – Fixed layout issues by adding proper spacing, borders, and positioning. Now, the form and preview sections …
> FIX: Keep Live Preview Box Sticky & Improve Form Layout (Issue No #50)

- index.html
- style.css
I added the hover effects on the page heading "Resume Creator" and also the other headings of each sections. That is if someone hovers the headings a underline will be visible and color of the heading will be changed.
Issue No. 52
> Add Hover Effects

- script.js
This PR implements the Auto-Save feature for the resume form, addressing Issue #53. Previously, refreshing the page resulted in complete data loss, forcing users to restart. Now, form data is automatically saved in local Storage and restored on page reload, that significantly improves the user experience.
Key Enhancements:............................................
1)  Auto-saves form data as users type.
2) Clears stored data upon successful form submission.
This prevents accidental data loss and ensures users don’t have to refill the entire form in case of a refresh.
@ishita-43  Let me know if any modifications are needed! Looking forward to your review.
> Enhanced Auto-Save Feature for Resume Form (Like Google Forms) –to Retain Data on Refresh #53

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
This PR adds standardized Issue and Pull Request templates to improve issue reporting and contribution quality. These templates will help maintain consistency, making it easier for contributors and maintainers to manage feature requests, bug reports, and PR submissions.
- Added .github/ISSUE_TEMPLATE/feature_request.md → A structured template for feature requests.
- Added .github/ISSUE_TEMPLATE/bug_report.md → A structured template for reporting bugs.
- Added .github/PULL_REQUEST_TEMPLATE.md → A structured PR template for better documentation and review process.
- Ensures well-defined feature requests and bug reports with relevant details.
- Encourages clear and informative PR descriptions, making code review more efficient.
- Improves overall collaboration and maintainability of the …
> PR and Issues Templates added

- index.html
- script.js
- style.css
I have resolved the navbar overlap issue with the form and improved the dark mode toggle button alignment. Additionally, it enhances the navbar's dynamic elements, including a typing effect on "Resume Creator", making the UI more engaging.
Fixes (issue no #63)
Fixed Navbar Overlapping Form
Dark Mode Toggle Button Fixed: Corrected misalignment and improved hover effects for a proper UI.
Dynamic Navbar Elements: I have Added a typing effect for the "Resume Creator" text, improving the visual appeal.
- [ YES] Bug fix (non-breaking change which fixes an issue)
- [ YES] New feature (non-breaking change which adds functionality)
- [NO ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ NO] Documentation update
Manually tested navbar positioning …
> the-navbar-is-fixed-and-enhanced   (Issue no- #63)

- styles/landing-page.css
- styles/style.css
> Made the modification

- pages/landing-page.html
@ishita-43 
So., as mentioned  in the issue no #67 ,
I successfully implemented the feature "dynamic floating particle in the background of the Landing page.
The particles will flawlessly move and get bounce back hitting the edges and the page elements.
- [ YES] New feature (non-breaking change which adds functionality)
Manually tested my self on my PC.
This addition doesn't disrupt the core functionality, structure, visibility or style of the current UI whatsoever.
- [YES ] I have performed a self-review of my code.
> Implemented dynamic floating particle animation at the home-page background  (Using Canvas API). ISSUE- #67

- pages/index.html
- pages/landing-page.html
- styles/landing-page.css
This PR optimises the SEO of the website by adding necessary meta tags in the HTML files.
Fixes #61 
- NA
> SEO Optimised by adding Meta Tags

- styles/style.css
This PR fixes the position of Navbar on the Resume Cretion page so that it remains fixed at the top with proper alignment of icons. Also it fixes the misalignment of to top button. I have also added a glassmorphism effect in the navbar for better visibility of different elements.
Fixes #73
> Position of Navbar fixed on Resume Creation Page

- js/script.js
- pages/index.html
- styles/style.css
hey, @ishita-43 , as mentioned in issue no #82 
I have Added an interactive floating cluster background animation using Particles.js to enhance visual appeal. Please check it out.
Fixes # (issue)
The UI is no more having a dull static baclground, This feature adds a dynamic touch, improving aesthetics and user experience.
- [YES ] New feature (non-breaking change which adds functionality)
I have manually tested ,this addition does not make any interruption to the core functionality, overall layout of the page whatsoever.
- [ SURE] My code follows the style guidelines of this project.
- [ YES] I have commented my code, particularly in hard-to-understand areas.
> Enhanced the Form page background with dynamic animation using particles .js (Issue no- #82) 

- pages/index.html
- styles/style.css
> Made the changes

- pages/index.html
- pages/landing-page.html
- styles/landing-page.css
- styles/style.css
- Fixed responsiveness issues across different screen sizes.
- Improved navigation behavior for smaller devices.
- Adjusted layout for better mobile usability.
Fixes #56
> Responsiveness of website fixed

- js/script.js
- pages/index.html
- styles/style.css
Fixed the main page layout and structuring.
Fixes #88 
- [ YES] Bug fix (non-breaking change which fixes an issue)
I tested every single functionality on my laptop, before making the PR. I can assure you, it works as intended.
- [SURE ] My code follows the style guidelines of this project.
- [SURE ] I have performed a self-review of my code.
- [ YES] My changes generate no new warnings.
> Fixed the main page layout and structuring (Issue- #88)

- pages/Register.html
- styles/Register.css
Navigation bar is added in the Register page. 
Fixes # (issue) :
Previously, the register page was missing the same nav bar as the landing page , and hence if one user moves to the register page from the landing page ,user will stuck in that page since there is no navigation options.(as the page just do Dummy Auth) .
- [YES ] New feature (non-breaking change which adds functionality)
Manually  tested .
- [SURE ] I have performed a self-review of my code.
- [YeS ] My changes generate no new warnings.
> Navigation bar is implimented in the Register page. (Issue no- #86)

- pages/index.html
- pages/landing-page.html
- styles/Register.css
- styles/footer.css
- styles/landing-page.css
- styles/style.css
Added a responsive and minimal footer component to the website. The footer includes copyright information, navigation links (Home, Create Resume), and placeholder links for Privacy Policy and Terms of Service. It enhances overall UI consistency and provides essential site-wide navigation.
Fixes #57
> Footer Added

- pages/index.html
- styles/style.css
I have made improvement on Main page footer section . Gave them a  professional, and responsive layout .
Fixes #95 
PREVIOUSLY: ..............................................
AFTER THE CHANGES.................................................
1)
2)
3)
- [ YES] My changes generate no new warnings.
> Main page footer enhanced (ISSUE no-#95)

- pages/landing-page.html
- styles/landing-page.css
As mentioned in the Issue no- #99 
The Elements in the Footer section of the LANDING PAGE were messy and not well organized , I get it fixed , gave a professional and aesthetic structure also some hover effect on the social icons etc  .
PREVIOUSLY...................................
AFTER THE CHANGES.............................................
This addition doesnt alter or interrupt any of the other functionality or structure of the page .
- [YES ] I have performed a self-review of my code.
- [YeS ] I have commented my code, particularly in hard-to-understand areas.
- [ YES] My changes generate no new warnings.
> The footer section of the landing page improved .(ISSUE no- #99 ).

- js/script.js
- pages/index.html
- styles/style.css
The generator now accept multiple entries for data
Fixes #16 
https://github.com/user-attachments/assets/d1833637-8d2e-4048-ae4e-27f7b0e88723
> Multiple Entries

- pages/Register.html
- pages/landing-page.html
- styles/Register.css
- styles/landing-page.css
Previously ,the “Contact” link in the navbar was non-functional . I implemented a dummy contact popover) that will appear on a click, positioned near the button itself  with a floating box-shadow effect and close button.
User can close this dialog box with clicking the 'X' mark or anywhere in the webpage.
Fixes #104 
- [YES ] New feature (non-breaking change which adds functionality)
Manually tested , made sure It doesnt create any new issue to the web page.
- [YeS ] I have commented my code, particularly in hard-to-understand areas.
> A Contact information popover For the Home page implemented.(ISSUE -104)

- styles/style.css
So, as mentioned in issue #115 ,
I got it fixed ,without effecting the overall structure of the viewport. Now the form looks all consistent and  aesthetic .
Fixes #115 
- [ YeS] Bug fix (non-breaking change which fixes an issue)
manually tested, made sure changes doesn't effect any of the viewport layout, structuring etc.
PRIVIOUSLY:....................
HERE IS HOW IT LOOKS AFTER THE CHANGES :..............................................
https://github.com/user-attachments/assets/e79eb5bd-ac74-473d-82e2-de433c4253e6
- [ YES] I have commented my code, particularly in hard-to-understand areas.
> Fixed the Uneven structuring of different sections for the Form. (Issue -no #115)

- pages/landing-page.html
- styles/landing-page.css
As mentioned in #117 ,
I have successfully given the intended functionality to teh "About" button in the navigation bar.
When clicked, it will trigger a popup card centered on the screen that will provide precise overview of the application. The background will blur to focus attention on the popup.
Fixes #117 
- [YES ] New feature (non-breaking change which adds functionality)
Manually tested.
https://github.com/user-attachments/assets/71618dce-4a80-482f-ac73-f7dd0410c626
> Home page popover about card implemented. (Issue no-#117)

- pages/about.html
- pages/landing-page.html
- styles/about.css
This PR adds a separate about page for the website maintaining its current style.
Fixes #59
> About Page Added

- js/script.js
- pages/index.html
- styles/style.css
@ishita-43 
As you probably did't noticed The Form page About  Still doesnt exists, the previous mage just overridden my about popover in the Home page(Landing page),
Here it is,plese check it out.....
https://github.com/user-attachments/assets/ddca1dc4-0738-4ce0-b760-5851cd33d7d0
AFTER MY CHANGES..................................
https://github.com/user-attachments/assets/c74cc732-0b80-40d3-91d2-600ad6f0b5a6
Fixes #125
> FORM PAGE-about-section-attached ,It was missing.(Issue -no #125)

- pages/contact.html
- pages/landing-page.html
- styles/contact.css
This PR adds a separate contact page for the website maintaining its current style.
Fixes #60
> Contact Page Added

- styles/style.css
> Update the name and description section

- README.md
I noticed a small mistake in the README file that I initially missed during my earlier contribution. This PR corrects that error to improve clarity and consistency. Apologies for the oversight!
> Fix minor mistake in README

- js/script.js
- pages/index.html
- styles/style.css
Issue no- #126 ,
@ishita-43 
As mentioned in the issue no #126 ,
i have implemented missing contact information as a pop over card, keeping entire form in the background  and blurred while it shoes up. 
**(IN the FORM PAGE).** 
Here is how it looks after my changes....................
https://github.com/user-attachments/assets/ce8f6588-28cb-4837-96b5-872c063abb9b
> Form page Missing contact attached .(Issue no- #126)

- js/script.js
- pages/index.html
- styles/style.css
Issue No #135 ,
The Dragging effect on Selecting input text is fixed. Now user can select the input text and form wont be dragged.
AFTER THE FIX:   .................................
https://github.com/user-attachments/assets/03adb48b-027a-42fb-aa07-0ffcf10de29b
> FIXED : The Dragging effect on Selecting input text is fixed.(Issue no-#135)

- styles/style.css
Added custom scroll bar for both the resume-generator form and the whole page
Fixes #127
> Added Custom Scrollbar

- js/script.js
- pages/index.html
- styles/style.css
https://github.com/user-attachments/assets/95fe3251-0523-411b-a4ae-bb90b269ac77
Issue : #140 ,
So ,as mentioned In this PR i have implemented back-to-top for the Form and got rid of the non functional page back to top button.
And of course i made sure this addition doesn't alter or interrupt rest of the things.
> Implemented back-to-top for the Form and got rid of the non functional page back to top button.(Issue no-#140)
